apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/giladravid16/konflux-pipelines?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: konflux-pipelines-test
    appstudio.openshift.io/component: konflux-pipelines-test
    pipelines.appstudio.openshift.io/type: build
  name: konflux-pipelines-test-on-push
  namespace: rh-ee-gravid-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/rh-ee-gravid-tenant/konflux-pipelines-test:{{revision}}
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: .
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/giladravid16/konflux-pipelines.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/service-component-pipeline.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-konflux-pipelines-test
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
